Update DSL to version 9.12.4
finos/rune-testing pull request #147
Opened 2024-06-27 16:48 UTC by hugohills-regnosys

Please include a summary of the change and the issue/story number.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

2024-06-27 16:48 UTC, davidalk approved these changes

2024-06-28 07:00 UTC, SimonCockx requested changes
This one also needs the jaxb dependency that got removed. See https://github.com/finos/rune-testing/commit/f94ceccd361b3a6474239856747e0235559e5ba3#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L237

2024-06-28 09:39 UTC, SimonCockx submitted a review, later dismissed

2024-06-28 10:14 UTC, SimonCockx approved these changes

2024-06-28 10:15 UTC, PayalKhanna approved these changes

2024-07-01 09:54 UTC, merged